FROM ubuntu:23.10
LABEL maintainer=rastislav.kish@protonmail.com

ENV REFRESHED_AT=12.11.2023

ADD clipshare_server /usr/local/bin/clipshare_server

CMD ["/usr/local/bin/clipshare_server"]

EXPOSE 3127

